#! /usr/bin/env python
"""
Redeye - A computer vision tool
"""
from basic import image_basic
from features import extraction
from shellparser import parser


def main():
    """
    Main caller for shell
    """
    image_basis = image_basic.BasicImage()
    filter_basis = image_basic.FilterImage()
    extractor = extraction.ExtractFeaturesImage()
    parse = parser.Parser()

    args = parse.construct_parser()

    file_list = image_basis.file_list(args.path)

    for ofile in file_list:
        im_obj = image_basis.open_image(ofile)

        if im_obj:
            if args.colorspace:
                image_basis.save(
                    image_basis.color_space(im_obj, args.colorspace, size=2),
                    ofile
                )
            elif args.resize:
                image_basis.save(
                    image_basis.resize(
                        im_obj, args.resize[0],
                        args.resize[1]),
                    ofile
                )
            elif args.rotate:
                image_basis.save(image_basis.rotation(im_obj, args.rotate), ofile)
            elif args.thumbs:
                image_basis.save(
                    image_basis.thumbs(
                        im_obj, args.thumbs[0], args.thumbs[1]
                    ),
                    ofile
                )
            elif args.crop:
                image_basis.show(
                    image_basis.crop(
                        im_obj, (
                            args.crop[0], args.crop[1],
                            args.crop[2], args.crop[3]
                        )
                    )
                )
            elif args.histogram:
                image_basis.histogram(im_obj, ofile)
            elif args.negative:
                image_basis.save(image_basis.negative(im_obj), ofile)
            elif args.darken_dark_pixels:
                filter_basis.polynomial_graylevel_transform(
                    im_obj, args.darken_dark_pixels
                ).save(ofile)
            elif args.dominant_colors:
                print ofile
                extractor.dominant_colors(im_obj, args.dominant_colors)
            elif args.dominant_colors_tuna:
                print ofile
                extractor.dominant_colors_tuna(im_obj, args.dominant_colors_tuna)

if __name__ == '__main__':
    main()
